### ISSUE TITLE
RollupError: "fullFormats" is not exported 

### ISSUE THREAD

**Issue by DerMolly** [json-layout/json-layout#1]
When running `npm build` on this PR https://github.com/EVerest/everest-admin-panel/pull/9 I get the following error message. I think the problem has something to do with vite and this project, but I'm unsure how to move forward. Especiall since I can verify that the "missing" export is there in `node_modules/ajv-formats/dist/formats.js`

```
error during build:
RollupError: "fullFormats" is not exported by "node_modules/ajv-formats/dist/formats.js", imported by "node_modules/@json-layout/vocabulary/src/normalized-layout/validate.js".
file: /Users/molly/Developer/everest-admin-panel/node_modules/@json-layout/vocabulary/src/normalized-layout/validate.js:1:9
1: import { fullFormats } from "ajv-formats/dist/formats.js";
            ^
2: // @ts-ignore
3: export const validate = validate59;export default validate59;const schema53 = {"$id":"https://json-layout.github.io/n...
    at getRollupEror (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at error (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/parseAst.js:372:42)
    at Module.error (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:13651:16)
    at Module.traceVariable (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:14099:29)
    at ModuleScope.findVariable (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:11802:39)
    at MemberExpression.bind (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:8603:49)
    at VariableDeclarator.bind (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:4732:23)
    at VariableDeclaration.bind (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:4728:28)
    at Program.bind (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:4728:28)
    at Module.bindReferences (file:///Users/molly/Developer/everest-admin-panel/node_modules/rollup/dist/es/shared/node-entry.js:13647:18)
```

**Comment by albanm** [comment]
Isn't this the same problem as this issue https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/422#issuecomment-1910894652 where you were also active ? Well one of the 2 problems discussed in the issue.

But the problem is not visible in my test project for now. I suppose it depends on whether or not dependencies are hoisted.

**Comment by DerMolly** [comment]
Somewhat. The key difference is that before the normal dev server `npm run vite` did not work. This works in the mean time and I can test and do everything I want, it just breaks the moment I run `npm run build`.

I just tested again with your [example project](https://github.com/koumoul-dev/vuetify-jsonschema-form/tree/next/app-examples/vite-typescript) and the build also fails there for me…

```
$ git status
On branch next
Your branch is up to date with 'origin/next'.

nothing to commit, working tree clean
$ npm install

added 173 packages, and audited 174 packages in 2s

40 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
$ npm run build

> vite-typescript@0.0.0 build
> vue-tsc --noEmit && vite build

vite v4.5.1 building for production...
✓ 581 modules transformed.
✓ built in 1.11s
"fullFormats" is not exported by "node_modules/ajv-formats/dist/formats.js", imported by "node_modules/@json-layout/vocabulary/src/normalized-layout/validate.js".
file: /private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/@json-layout/vocabulary/src/normalized-layout/validate.js:1:9
1: import { fullFormats } from "ajv-formats/dist/formats.js";
            ^
2: // @ts-ignore
3: export const validate = validate59;export default validate59;const schema53 = {"$id":"https://json-layout.github.io/n...
error during build:
RollupError: "fullFormats" is not exported by "node_modules/ajv-formats/dist/formats.js", imported by "node_modules/@json-layout/vocabulary/src/normalized-layout/validate.js".
    at error (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at MemberExpression.bind (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:9539:49)
    at VariableDeclarator.bind (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at VariableDeclaration.bind (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Program.bind (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
    at Module.bindReferences (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:13741:18)
    at Graph.sortModules (file:///private/tmp/vuetify-jsonschema-form/app-examples/vite-typescript/node_modules/rollup/dist/es/shared/node-entry.js:25853:20)
```

**Comment by albanm** [comment]
Ok, I missed that ! I will have a look.

**Comment by lukas-mertens** [comment]
@albanm can reproduce: https://asciinema.org/a/Fq1KfOHi2KB7ZSbaveqRJGf4a

**Comment by albanm** [comment]
Ok, this is really confusing. The build actually runs if I remove the build.commonjsOptions.include parameter that was defined precisely to fix it.

**Comment by lukas-mertens** [comment]
@albanm same for us, but in that case it didn't work at runtime anymore

**Comment by albanm** [comment]
Ok, I pushed a fix in the code compilation logic @json-layout/core (`import { fullFormats } from "ajv-formats/dist/formats.js"` instead of `import ajvFormats from "ajv-formats/dist/formats.js"`).

The new code was already applied to the validation code of @json-layout/vocabulary a few weeks ago (then I quickly forgot about it) and it looks like that is what breaks for you. But the old code breaks for newer versions of ajv-formats. I guess you need to update ajv-formats.

The example app in the vjsf repo is up to date on its dependencies and it looks like everything works ok, both in dev mode and after compilation.

**Comment by lukas-mertens** [comment]
@albanm I don't understand what I am doing wrong. I am explicitly installing the latest ajv-formats version 2.1.1

https://github.com/EVerest/everest-admin-panel/actions/runs/7994485372/job/21832640936?pr=9

As you can see in the pipeline run, it is still failing. Here is the [package.json](https://github.com/EVerest/everest-admin-panel/blob/9a9a756cecfb6492d4146eb01386ffe9d2d5007d/package.json)

**Comment by albanm** [comment]
Can you run `npm ls ajv-formats` just to be 100% sure that there is not multiple versions installed in subdirectories ?

Also my app example doesn't include anymore optimizeDeps and commonjsOptions, and it works fine without it. I honestly do not understand what makes these options necessary or not in different cases.

**Comment by lukas-mertens** [comment]
pnpm ls leads to:
![CleanShot 2024-02-21 at 21 00 06](https://github.com/json-layout/json-layout/assets/10901304/73d471c0-aebf-4b7f-8374-ccf57c474178)

When I remove the commonjs and build part the build works fine/vite starts properly:
![CleanShot 2024-02-21 at 21 04 40](https://github.com/json-layout/json-layout/assets/10901304/344e8e69-77cd-4495-bad7-5628054cd168)

but it fails at runtime:
![CleanShot 2024-02-21 at 21 05 48](https://github.com/json-layout/json-layout/assets/10901304/a28bdefa-401f-4eba-ba0f-3388ad260460)

The interesting thing: Vite (without build) works fine even with optimizeDeps and build:
![CleanShot 2024-02-21 at 21 07 09](https://github.com/json-layout/json-layout/assets/10901304/9a3f9f5d-0d29-47c1-9c7f-09415d793c3d)

But vite build doesn't:
![CleanShot 2024-02-21 at 21 08 21](https://github.com/json-layout/json-layout/assets/10901304/1c163298-e130-4752-a331-0602b4f05c0e)

**Comment by albanm** [comment]
You should look for any difference between your project and this one https://github.com/koumoul-dev/vuetify-jsonschema-form/tree/next/app-examples/vite-typescript and try to alter things. Difference could be pnpm vs npm, vite/rollup version, whether some dependencies are nested or not, etc.

**Comment by lukas-mertens** [comment]
@albanm Oh my good, I finally found the solution. What fixed it for me, was to install the commonjs plugin for rollup. The problem: vite uses a different build mechanism for dev builds and prod builds. That's why it was only failing in one: Only for the prod builds rollup is used for everything making it necessary to use the commonjs plugin. For the future: here is a working vite.config.ts (at least working for me):

```md
import Vue from '@vitejs/plugin-vue';
import Vuetify, {transformAssetUrls} from 'vite-plugin-vuetify';
import {defineConfig} from "vite";
import ViteFonts from 'unplugin-fonts/vite';
import {commonjsDeps} from '@koumoul/vjsf/utils/build';
import {fileURLToPath} from "node:url";
import commonjs from "@rollup/plugin-commonjs";

export default defineConfig({
    optimizeDeps: {
        include: commonjsDeps,
    },
    build: {
        commonjsOptions: {
            include: commonjsDeps,
        }
    },
    plugins: [
        commonjs(),
        Vue({
            template: { transformAssetUrls }
        }),
        Vuetify({
            autoImport: true,
        }),
        ViteFonts({
            google: {
                families: [ {
                    name: 'Roboto',
                    styles: 'wght@100;300;400;500;700;900',
                }],
            },
        })
    ],
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url))
        },
        extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json'],
    },
    server: {
        port: 8080,
    },
});

```

I think this issue can be closed, thanks for you support!

**Comment by lukas-mertens** [comment]
@DerMolly I think this issue can be closed
